version: "3"
services:
  app_prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: course-platform-app-prod
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
    depends_on:
      - db_prod
  db_prod:
    image: "postgres"
    container_name: course-platform-postgres-dev
    environment:
      - "POSTGRES_USER=testUser"
      - "POSTGRES_PASSWORD=testPassword"
      - "POSTGRES_DB=test-db"
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"