version: "3"

services:
  postgres:
    image: "postgres"
    container_name: course-platform-postgres
    environment:
      - "POSTGRES_USER=testUser"
      - "POSTGRES_PASSWORD=testPassword"
      - "POSTGRES_DB=course-platform"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data