version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: course-platform-app-dev
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    container_name: course-platform-postgres-dev
    environment:
      - "POSTGRES_USER=testUser"
      - "POSTGRES_PASSWORD=testPassword"
      - "POSTGRES_DB=course-platform"
    volumes:
      - .docker/dbdata/postgres:/var/lib/postgresql/data
    restart: always
    tty: true
    expose:
      - "5432"
    ports:
      - "5432:5432"